# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Add": "ToImport.ipynb",
         "ComposedModule": "import_chisel_mod.ipynb",
         "DoubleComposedMod": "import_composed_mod.ipynb",
         "ALUIO": "test.ipynb",
         "ALUSkeleton": "test.ipynb",
         "test.Add": "test.ipynb",
         "add": "test.ipynb",
         "Sub": "test.ipynb",
         "sub": "test.ipynb",
         "MulDiv": "test.ipynb",
         "mul": "test.ipynb",
         "div": "test.ipynb",
         "includeAdd": "test.ipynb",
         "includeSub": "test.ipynb",
         "includeMulDiv": "test.ipynb",
         "Operator": "test.ipynb",
         "OperatorTester": "test.ipynb",
         "FuncToNewScript": "test.ipynb",
         "FuncToNewScript2": "test.ipynb",
         "TestObj": "test.ipynb",
         "LotsOfParams": "test.ipynb",
         "testTypeParams": "test.ipynb"}

modules = ["ModA.sc",
           "ModB.sc",
           "ModC.sc",
           "test.sc",
           "NewScript.sc",
           "NewScript2.sc"]

packages = {"ComposedExample": ['ModC.sc', 'ModA.sc', 'ModB.sc'],
         "Examples": ['NewScript2.sc', 'test.sc', 'NewScript.sc']}

doc_url = "https://ucsc-vama.github.io/chisel_nbdev/"

git_url = "https://github.com/ucsc-vama/chisel_nbdev"

def custom_doc_links(name): return None
