# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Add": "ToImport.ipynb",
         "ComposedModule": "import_chisel_mod.ipynb",
         "DoubleComposedMod": "import_composed_mod.ipynb",
         "getMergeLevTwidsCachedParallel": "parallel_mergeNTT.ipynb",
         "TwiddleGenOTFParallel": "parallel_mergeNTT.ipynb",
         "apply": "parallel_mergeNTT.ipynb",
         "TwidFactory": "parallel_mergeNTT.ipynb",
         "getMemAddrs": "parallel_mergeNTT.ipynb",
         "getMemAddrsParallel": "parallel_mergeNTT.ipynb",
         "MemAddrGenParallel": "parallel_mergeNTT.ipynb",
         "AddrGenFactory": "parallel_mergeNTT.ipynb",
         "MergeNTTParallel": "parallel_mergeNTT.ipynb",
         "resetNTT": "parallel_mergeNTT.ipynb",
         "printState": "parallel_mergeNTT.ipynb",
         "printRF": "parallel_mergeNTT.ipynb",
         "ALUIO": "test.ipynb",
         "ALUSkeleton": "test.ipynb",
         "test.Add": "test.ipynb",
         "add": "test.ipynb",
         "Sub": "test.ipynb",
         "sub": "test.ipynb",
         "MulDiv": "test.ipynb",
         "mul": "test.ipynb",
         "div": "test.ipynb",
         "includeAdd": "test.ipynb",
         "includeSub": "test.ipynb",
         "includeMulDiv": "test.ipynb",
         "Operator": "test.ipynb",
         "OperatorTester": "test.ipynb",
         "FuncToNewScript": "test.ipynb",
         "FuncToNewScript2": "test.ipynb",
         "TestObj": "test.ipynb",
         "LotsOfParams": "test.ipynb"}

modules = ["ModA.sc",
           "ModB.sc",
           "ModC.sc",
           "ntt.sc",
           "test.sc",
           "NewScript.sc",
           "NewScript2.sc"]

doc_url = "https://ucsc-vama.github.io/chisel-nbdev//"

git_url = "https://github.com/ucsc-vama/chisel-nbdev"

def custom_doc_links(name): return None
