# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Add": "test.ipynb",
         "add": "test.ipynb",
         "Sub": "test.ipynb",
         "sub": "test.ipynb",
         "MulDiv": "test.ipynb",
         "mul": "test.ipynb",
         "div": "test.ipynb",
         "includeAdd": "test.ipynb",
         "includeSub": "test.ipynb",
         "includeMulDiv": "test.ipynb",
         "Operator": "test.ipynb"}

modules = ["ModA.sc",
           "ModB.sc",
           "ModC.sc",
           "test.sc"]

doc_url = "tbd/"

git_url = "https://github.com/ucsc-vama/chisel-nbdev"

def custom_doc_links(name): return None
