# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Add": "test.ipynb",
         "ComposedModule": "import_chisel_mod.ipynb",
         "DoubleComposedMod": "import_composed_mod.ipynb",
         "ALUSkeleton": "test.ipynb",
         "add": "test.ipynb",
         "Sub": "test.ipynb",
         "sub": "test.ipynb",
         "MulDiv": "test.ipynb",
         "mul": "test.ipynb",
         "div": "test.ipynb",
         "includeAdd": "test.ipynb",
         "includeSub": "test.ipynb",
         "includeMulDiv": "test.ipynb",
         "Operator": "test.ipynb",
         "FuncFromTest": "test.ipynb",
         "FuncToNewScript": "test.ipynb",
         "FuncToNewScript2": "test.ipynb"}

modules = ["ModA.sc",
           "ModB.sc",
           "ModC.sc",
           "test.sc",
           "NewScript.sc",
           "NewScript2.sc"]

doc_url = "tbd/"

git_url = "https://github.com/ucsc-vama/chisel-nbdev"

def custom_doc_links(name): return None
